config/routes.rb
Rails.application.routes.draw do
  resources :vens

  devise_for :usuarios
  root :to => 'inicio#index'
  resources :productos

  resources :empresas

  resources :clientes

  resources :vendedors

  get 'inicio/index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :ven
  has_many :vendedor, :through => :ven
  has_many :producto, :through => :ven


validates :nombre, :apellidoP ,:apellidoM, :direccion, :presence => { message: "No puede dejarse vacío" }
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
@vendedors = @cliente.vendedor.all
@productos = @cliente.producto.all

  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
  if @cliente.valid?
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    else
      format.html { render :new }
      format.json { render json: @cliente.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:rut, :nombre, :apellidoP, :apellidoM, :direccion, :comuna)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%# Ver CSS http://getbootstrap.com/css/%>
<%= form_for @cliente, :html => { :role=>"form", :class=>"form-horizontal" } do |f| %>
<div class="col-md-6">
<div class="form-group<%= @cliente.errors[:rut].any? ? " has-error has-feedback" : "" %>">
<%= f.label :rut, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :rut, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:rut].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:rut].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @cliente.errors[:nombre].any? ? " has-error has-feedback" : "" %>">
<%= f.label :nombre, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :nombre, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:nombre].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:nombre].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @cliente.errors[:apellidoP].any? ? " has-error has-feedback" : "" %>">
<%= f.label :apellidoP, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :apellidoP, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:apellidoP].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:apellidoP].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @cliente.errors[:apellidoM].any? ? " has-error has-feedback" : "" %>">
<%= f.label :apellidoM, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :apellidoM, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:apellidoM].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:apellidoM].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @cliente.errors[:comuna].any? ? " has-error has-feedback" : "" %>">
<%= f.label :comuna, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :comuna, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:comuna].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:comuna].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>
<div class="form-group<%= @cliente.errors[:direccion].any? ? " has-error has-feedback" : "" %>">
<%= f.label :direccion, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :direccion, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @cliente.errors[:direccion].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @cliente.errors[:direccion].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<%= f.hidden_field :usuario_id, :value => current_usuario.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

 <div class="col-md-4"></div>
</div>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Detalle', @cliente %> |
<%= link_to 'Vlver', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table  class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th>Direccion</th>
      <th>Comuna</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.rut %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellidoP %></td>
        <td><%= cliente.apellidoM %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.comuna %></td>
        <td><%= link_to 'Detalle', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: '¿Estas seguro de Eliminar al cliente?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Ingreso de Clientes</h1>

<%= render 'form' %>

<%= link_to 'Volver', clientes_path %>

app/views/clientes/show.html.erb
<p>
  <strong>Rut:</strong>
  <%= @cliente.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<div class="col-md-3">
<h2>Ventas</h2>
<table class="table table-bordered">

<thead>
  <tr>
    <th>Producto</th>
    <th>Tipo</th>



</tr>
  </thead>
<tr>

  <% @productos.each do |producto| %>
    <td><%= producto.nombre %></td>
    <td><%= producto.tipo %></td>




  </tr>
  <% end %>
</table>
  <table class="table table-bordered">

  <thead>
    <tr>

        <th>Vendedor</th>

        </tr>
          </thead>
        <tr>
<% @vendedors.each do |vendedor| %>
  <td><%= vendedor.nombre %></td>




  </tr>
<% end %>
</table>

</div>

<div class="col-md-3"></div>
</div>
<%= link_to 'Editar', edit_cliente_path(@cliente) %>
<%= link_to 'Volver', clientes_path %>