config/routes.rb
Rails.application.routes.draw do
  resources :vens

  devise_for :usuarios
  root :to => 'inicio#index'
  resources :productos

  resources :empresas

  resources :clientes

  resources :vendedors

  get 'inicio/index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <% if usuario_signed_in? %>
    <div class="navbar-header">
      <a class="navbar-brand" href="<%=root_path%>">Inicio</a>
      <a class="navbar-brand" href="<%=productos_path%>">Productos</a>
      <a class="navbar-brand" href="<%=clientes_path%>">Clientes</a>
      <a class="navbar-brand" href="<%=vendedors_path%>">Vendedores</a>
      <a class="navbar-brand" href="<%=empresas_path%>">Empresa</a>
      <a class="navbar-brand" href="<%=vens_path%>">Ventas</a>
    </div>



      </form>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menú<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%=root_path%>">Inicio </a></li>
              <li role="separator" class="divider"></li>
            <li><a href="<%=productos_path%>">Productos</a></li>
            <li><a href="<%=clientes_path%>">Clientes</a></li>
            <li><a href="<%=vendedors_path%>">Vendedores</a></li>
            <li><a href="<%=empresas_path%>">Empresa</a></li>
            <li><a href="<%=vens_path%>">Ventas</a></li>


      
          </ul>
        </li>
        <li><a href="<%= edit_usuario_registration_path(current_usuario)%>">Editar Perfil</a></li>
        <li><a href="<%=destroy_usuario_session_path %>", data-method="delete">Cerrar Sesion</a></li>

      <% else %>


      <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= new_usuario_session_path%>">Ingresar</a></li>
          <li><a href="<%=new_usuario_registration_path %>">Registrarse</a></li>
        </ul>
      <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>