config/routes.rb
Rails.application.routes.draw do
  resources :vens

  devise_for :usuarios
  root :to => 'inicio#index'
  resources :productos

  resources :empresas

  resources :clientes

  resources :vendedors

  get 'inicio/index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :empresa
  has_many :ven
  has_many :vendedor, :through => :ven


   validates :nombre, :presence => { message: "No puede dejarse vacío"}
   validates :codigo, :presence => { message: "No puede dejarse vacío"}
   validates :tipo, :presence => { message: "No puede dejarse vacío"}
   validates :valor, :presence => { message: "No puede dejarse vacío"}
   validates :empresa, :presence => { message: "No puede dejarse vacío"}
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:codigo, :nombre, :tipo, :valor, :empresa_id)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%# Ver CSS http://getbootstrap.com/css/%>
<%= form_for @producto, :html => { :role=>"form", :class=>"form-horizontal" } do |f| %>
<div class="col-md-6">
<div class="form-group<%= @producto.errors[:codigo].any? ? " has-error has-feedback" : "" %>">
<%= f.label :codigo, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :codigo, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @producto.errors[:codigo].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @producto.errors[:codigo].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @producto.errors[:nombre].any? ? " has-error has-feedback" : "" %>">
<%= f.label :nombre, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :nombre, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @producto.errors[:nombre].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @producto.errors[:nombre].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @producto.errors[:tipo].any? ? " has-error has-feedback" : "" %>">
<%= f.label :tipo, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :tipo, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @producto.errors[:tipo].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @producto.errors[:tipo].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>


<div class="form-group<%= @producto.errors[:valor].any? ? " has-error has-feedback" : "" %>">
<%= f.label :valor, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :valor, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @producto.errors[:valor].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @producto.errors[:valor].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>







<div class="form-group<%= :empresa_id %>">
<%= f.label :empresa_id, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.select( "empresa_id",Empresa.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Selecciona Empresa'}) %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>

</div>
</div>

<%= f.hidden_field :usuario_id, :value => current_usuario.id %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<div class="col-md-4"></div>
</div>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Detalle', @producto %> |
<%= link_to 'Volver', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>Empresa</th>
      <th colspan="3"> Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.codigo %></td>
        <td><%= producto.nombre %></td>
        <td><%= producto.tipo %></td>
        <td><%= producto.valor %></td>
        <td><%= producto.empresa.nombre%></td>
        <td><%= link_to 'Detalle', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: '¿Estas seguro de Eliminar el Producto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingresar Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Volver', productos_path %>

app/views/productos/show.html.erb
<p>
  <strong>Codigo:</strong>
  <%= @producto.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @producto.tipo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @producto.valor %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @producto.empresa.nombre %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto) %> 
<%= link_to 'Volver', productos_path %>