config/routes.rb
Rails.application.routes.draw do
  resources :vens

  devise_for :usuarios
  root :to => 'inicio#index'
  resources :productos

  resources :empresas

  resources :clientes

  resources :vendedors

  get 'inicio/index'

end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
  has_many :ven
  has_many :producto, :through => :ven
  validates :nombre, :apellidoP ,:apellidoM, :correo, :presence => { message: "No puede dejarse vacío" }
end

app/controllers/vendedors_controller.rb
 class VendedorsController < ApplicationController
  before_action :set_vendedor, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_usuario!
  # GET /vendedors
  # GET /vendedors.json
  def index
    @vendedors = Vendedor.all
  end

  # GET /vendedors/1
  # GET /vendedors/1.json
  def show
@productos = @vendedor.producto.all
  end

  # GET /vendedors/new
  def new
    @vendedor = Vendedor.new
  end

  # GET /vendedors/1/edit
  def edit
  end

  # POST /vendedors
  # POST /vendedors.json
  def create
    @vendedor = Vendedor.new(vendedor_params)

    respond_to do |format|
      if @vendedor.save
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully created.' }
        format.json { render :show, status: :created, location: @vendedor }
      else
        format.html { render :new }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendedors/1
  # PATCH/PUT /vendedors/1.json
  def update
    respond_to do |format|
      if @vendedor.update(vendedor_params)
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendedor }
      else
        format.html { render :edit }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendedors/1
  # DELETE /vendedors/1.json
  def destroy
    @vendedor.destroy
    respond_to do |format|
      format.html { redirect_to vendedors_url, notice: 'Vendedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor
      @vendedor = Vendedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendedor_params
      params.require(:vendedor).permit(:rut, :nombre, :apellidoP, :apellidoM, :correo)
    end
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/vendedors/_form.html.erb
<%# Ver CSS http://getbootstrap.com/css/%>
<%= form_for @vendedor, :html => { :role=>"form", :class=>"form-horizontal" } do |f| %>
<div class="col-md-6">
<div class="form-group<%= @vendedor.errors[:rut].any? ? " has-error has-feedback" : "" %>">
<%= f.label :rut, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :rut, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @vendedor.errors[:rut].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @vendedor.errors[:rut].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @vendedor.errors[:nombre].any? ? " has-error has-feedback" : "" %>">
<%= f.label :nombre, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :nombre, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @vendedor.errors[:nombre].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @vendedor.errors[:nombre].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>


<div class="form-group<%= @vendedor.errors[:apellidoP].any? ? " has-error has-feedback" : "" %>">
<%= f.label :apellidoP, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :apellidoP, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @vendedor.errors[:apellidoP].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @vendedor.errors[:apellidoP].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @vendedor.errors[:apellidoM].any? ? " has-error has-feedback" : "" %>">
<%= f.label :apellidoM, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :apellidoM, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @vendedor.errors[:apellidoM].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @vendedor.errors[:apellidoM].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>

<div class="form-group<%= @vendedor.errors[:correo].any? ? " has-error has-feedback" : "" %>">
<%= f.label :correo, :class=>"col-sm-2 control-label" %>
<div class="col-sm-5">
  <%= f.text_field :correo, :class => 'form-control' %>
  <%#Obtener solo el mensaje con la expresion regular /\w([^]*)/%>
  <%if @vendedor.errors[:correo].any? %>
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
    <p class="bg-warning"><%= @vendedor.errors[:correo].to_s[/\w([^"]*)/] %></p>
  <% end -%>
</div>
</div>



        <%= f.hidden_field :usuario_id, :value => current_usuario.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="col-md-4"></div>
</div>

app/views/vendedors/edit.html.erb
<h1>Editing vendedor</h1>

<%= render 'form' %>

<%= link_to 'Detalle', @vendedor %> |
<%= link_to 'Volver', vendedors_path %>

app/views/vendedors/index.html.erb
<h1>Listing vendedors</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Apellidop</th>
      <th>Apellidom</th>
      <th>Correo</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @vendedors.each do |vendedor| %>
      <tr>
        <td><%= vendedor.rut %></td>
        <td><%= vendedor.nombre %></td>
        <td><%= vendedor.apellidoP %></td>
        <td><%= vendedor.apellidoM %></td>
        <td><%= vendedor.correo %></td>
        <td><%= link_to 'Detalle', vendedor %></td>
        <td><%= link_to 'Editar', edit_vendedor_path(vendedor) %></td>
        <td><%= link_to 'Eliminar', vendedor, method: :delete, data: { confirm: '¿Estas seguro de Eliminar al Vendedor?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendedor', new_vendedor_path %>

app/views/vendedors/new.html.erb
<h1>New vendedor</h1>

<%= render 'form' %>

<%= link_to 'Volver', vendedors_path %>

app/views/vendedors/show.html.erb
<p>

  <strong>Rut:</strong>
  <%= @vendedor.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @vendedor.nombre %>
</p>

<p>
  <strong>Apellidop:</strong>
  <%= @vendedor.apellidoP %>
</p>

<p>
  <strong>Apellidom:</strong>
  <%= @vendedor.apellidoM %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @vendedor.correo %>
</p>
<br>
<a class="btn btn-default btn-lg active" href="<%=edit_vendedor_path %>" role="button">Editar</a>
<a class="btn btn-default btn-lg active" href="<%=vendedors_path %>" role="button">Volver</a>



<h2>Ventas</h2>
<table class="table table-bordered">

<thead>
  <tr>
    <th>Producto</th>
    <th>Tipo</th>


</tr>
</thead>

<tbody>
  <% @productos.each do |producto| %>
<tr>
    <td><%= producto.nombre %></td>
    <td><%= producto.tipo %></td>
  <% end %>


</tr>


</tbody>
</table>